### ISSUE TITLE
Do you have tested the four-cameras setup?

### ISSUE THREAD

**Issue by YiChenCityU** [GaoHongchen/okvis_cg#1]
Hi, thanks very much for your share. 
Do you have the dataset with four cameras? How to do it?

**Comment by cggos** [comment]
@YiChenCityU 
i so sorry i dont have the dataset with four camera and where to find it :cry:

**Comment by cggos** [comment]
@YiChenCityU 
I found the Three Camera Dataset **[LaFiDa](http://www.ipf.kit.edu/lafida.php) - A Laserscanner Multi-Fisheye Camera Dataset** which may be useful for you!

**Comment by YiChenCityU** [comment]
It's great. Thanks for your reminding.
