### ISSUE TITLE
无法运行roslaunch okvis_ros okvis_node_mynteye_s1030_stereo.launch rviz:=true

### ISSUE THREAD

**Issue by Grandzxw** [GaoHongchen/okvis_cg#2]
[okvis_node_mynteye_s1030_stereo.launch] is neither a launch file in package [okvis_ros] nor is [okvis_ros] a launch file name
The traceback for the exception was written to the log file
请问楼主是什么问题呢?

**Comment by cggos** [comment]
代码中launch文件改了，README.md中的命令没有及时更新，可尝试下面命令：

```sh
roslaunch okvis_ros okvis_node_mynteye.launch rviz:=true
```
